version: '3.7'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      uvicorn app:app
      --host 0.0.0.0
      --port 8000
      --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - ./typesense-data:/data
    environment:
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY}
    command:
      - "--api-key=${TYPESENSE_API_KEY}"
      - "--data-dir=/data"

networks:
  myapp-net:
    driver: bridge
